version: '3.9'

services:
  app:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - PYTHONPATH=/app/src
    depends_on:
      - db

  db:
    image: postgres:15 
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tests:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - PYTHONPATH=/app/src
    command: pytest tests/
    volumes:
      - ./backend:/app

volumes:
  postgres_data: